### ISSUE TITLE
Update browser logos

### ISSUE THREAD

**Issue by mathiasbynens** [justmarkup/bugspencer.com#5]
Some of the browser logos used on this site are outdated. (The ones for Chrome and Opera, for example, and possibly others.)

You can get up-to-date versions here: https://github.com/alrra/browser-logos

**Comment by mathiasbynens** [comment]
When will these changes be live? Just wondering — there’s no rush :)

**Comment by justmarkup** [comment]
The updates should be already live - a hard refresh should do the trick.

**Comment by mathiasbynens** [comment]
I had tried a hard refresh before posting here. It does work in an incognito window (or in another browser that doesn’t have the service worker installed yet).

After looking into it a bit more, it seems the service worker is returning the cached version.

**Comment by justmarkup** [comment]
Ah, yes the old service worker was still active. Updated the service worker script, bumped version and added skipWaiting() on install event and a function to clear old caches to prevent this in the future.

**Comment by mathiasbynens** [comment]
:+1:
